---
- name: Copy Wordpress script to remote host
  template:
    src: ./roles/wordpress/templates/start.sh
    dest: /tmp/wordpress/start.sh

- name: Build Worpress image from Dockerfile
  community.docker.docker_image:
    name: wordpress
    tag: my_img
    source: build
    build:
      path: /tmp/wordpress

- name: Run nginx Container
  community.docker.docker_container:
    name: wordpress
    image: wordpress:my_img
    restart_policy: always
    exposed_ports:
      - "9000:9000"
    volumes:
      - web_data:/var/www/html
    networks:
      - name: inception_network