---
- name: Copy entrypoint file
  template:
    src: ./roles/database/templates/configure.sh
    dest: /tmp/mariadb/configure.sh
    mode: '0755'

- name: Build Mariadb image from dockerfile
  community.docker.docker_image:
    name: mariadb
    tag: my_img
    source: build
    build:
      path: /tmp/mariadb/

- name: Run mariadb container
  community.docker.docker_container:
    name: mariadb
    image: mariadb:my_img
    state: started
    restart_policy: always
    env:
      MARIADB_ROOT_PASSWORD: "{{ MARIADB_ROOT_PASSWORD }}"
      MARIADB_DATABASE: "{{ MARIADB_DATABASE }}"
      MARIADB_USER: "{{ MARIADB_USER }}"
      MARIADB_PASSWORD: "{{ MARIADB_PASSWORD }}"
    volumes:
      - database:/var/lib/mysql
    networks:
      - name: inception_network